### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by chavab1** [catpointer/mod_catpointer_articles#5]
Hi Roberto, I came across your video while doing research to try to implement TDD on my projects.

I'm following along your video but I'm a little confused. First off, I'm fairly new to Joomla so please bare with me if I seem a little lost. I'm trying to copy your file structure but I'm struggling to figure out how to set it up on my environment. I'm using my test module directory as the root where I have my composer.json and phpunit.xml files. However, on your `mod_catpointer_articles` directory you also have an `/extensions/modules/site/mod_catpointer_articles` directory nested within. Am I suppose to create another directory inside my module directory or do I have to move my root to the root of the website??

Thank you very much for help in advance

**Comment by phproberto** [comment]
Hey @chavab1!

Thanks for watching my video and being interested on it. I'm really happy to receive feedback from it! :)

When developing Joomla! extensions one of the main issues devs have to deal with is how to integrate the development process with a joomla website to test what you are actually programming. 

Using this repository as an example you usually have a joomla website to test the extension in your htdocs/www folder:

`/var/www/mywebsite.com`

and then the folder containing the clone of this repo which contains the extension code:

`/home/roberto/code/mod_catpointer_articles`

When you are modifying the site you don't want having to reinstall your extension every time you make a change on it to test it.

There is people that prefers to create symbolic links between the extension repository and a joomla website but for me that's not an option because you can end removing/losing files from your extension repository if you haven't commited them to git. It happened to me in the past and I find it a very dangerous practice.

What I use is [joomla-gulp](https://github.com/phproberto/joomla-gulp). It's a system that asks you where is your testing site (`/var/www/mywebsite.com` in our example) and watches your extension folder. When you change something in the extension Gulp detects the change, updates the site files and refreshes the browser. So you can develop almost in real time being sure that you won't lose anything.

I use the same folder structure on all my repositories:

* `build`. This folder includes all the stuff to build the extensions. Copying them to the testing site, generating a zip for the current version, compiling Sass/LESS files into CSS, concatenate and minimise JS files... Than kind of stuff.
* `extensions`. Code that can be zipped and installed on any website. The real code of the joomla extensions being distributed. You can use install from folder from joomla pointing to that folder and the extensions will be installed without issues. I like to keep it isolated and ready to be used.
* `tests`. All the testing related stuff.

This is just a module so it's a bit odd to see the content of the `extensions` folder but it usually contains more stuff. Now you just have:

* `extensions`
    * `modules`
        * `site`
            * `mod_catpointer_articles`

But it usually can be something like:

* `extensions`
    * `components`
        * `com_example`
    * `libraries`
        * `catpointer`
    * `modules`
        * `admin`
            * `mod_latest_products`
        * `site`
            * `mod_catpointer_articles`
    * `plugins`
        * `system` 
            * `catpointer`
        * `authentication`
            * `email`
    * `templates`
        * `site`
            * `phproberto`

Using the same structure even if I only have 1 extension gives me some benefits:

* I have convention I can follow without letting my brain to think when I create an extension.
* I can add more extensions to my repositories easily without having to change their structure.
* I can reuse testing related stuff like libraries, etc.
* I can reuse build related stuff like gulp scripts for each extension

Of course you don't have to follow my conventions or to use joomla-gulp to use TDD on your extensions. I also use other structures like:

https://github.com/phproberto/joomla-flysystem

But I use that mainly for stuff that can be installed through composer. 

If you use a different folder structure you have to replace all the references to the `extensions` folder with your own structure in: 

* [tests bootstrap.php file](https://github.com/CatPointer/mod_catpointer_articles/blob/develop/tests/bootstrap.php#L17) 
* [phpunit.xml file](https://github.com/CatPointer/mod_catpointer_articles/blob/develop/phpunit.dist.xml#L23)

**Comment by chavab1** [comment]
Thank you very much for your quick reply. 

OK, I understand now. So you do have separate directories for the actual Joomla site and the module. That's where I was confused but it makes sense now. I really like how you set up your directory structure.

Question, what advice would you give me to setup a workflow to add testing to installed extensions on an existing live site? I took over some projects from a previous developer and I've found that there are some bugs on several of the custom extensions. So what I want to do is integrate testing on these extensions to make it part of the workflow. We have some elaborate components that I'm routinely asked to add more features to. I think having a good testing system set up would really help out with current and any new extensions.

Our current workflow is setup is as follow: 
- Live sites are hosted on a CPanel
- We use PerForce for version control
- Local repo is used in development environment
- Changes are checked-in to PerForce and then SFTPd to Cpanel


Thank you very much for your information and help.

**Comment by phproberto** [comment]
I have a different approach depending on the kind of extension that has the bug:

* **Commercial extensions**. Patching commercial extensions is not a good idea. There is a team maintaining them and you may stop working with X client leaving them without official + your support. The best you can do is to refer to official channels to report the issue (or even submit a patch). 
* **Custom extensions**. This includes extensions that were created by previous developers specifically for this client or extensions that the client installed and do not have official support anymore. In these cases I create a separated repository specifically for those extensions. I don't like to mix my code with previous extensions because I want the client to know that my code is in X repo and the `legacy` code is in Y repo. But this really depends on the plan you have for that extension. In this case tests would work exactly the same as in your extension repo.

To tests sites another option is to use end-to-end tests. Those tests forget the internal implementation and focus on real user things like:

* User can register
* User can login
* User can buy a product

These tests are cool because is the top level behaviour of a site but they usually depend on the UI so they are easy to break (when you change your markup) and that makes them the most expensive to maintain. 

If you want to use end-to-end testing I'd use [cypress.io](https://www.cypress.io) which is the easiest (and funniest) way to get started nowadays.

**Comment by chavab1** [comment]
Thank you very much Roberto.

Yeah, I was talking just about custom extensions. I wouldn't date to try to mess with the code of commercial or core extensions.

I really appreciate you bringing up end-to-end testing. That was going to be my next venture. But I wanted to first get a good handle on unit testing. I'll def look into [cypress.io](https://www.cypress.io/) .

Once again, thank you very much for your very informative video, files and follow-up information. You've def put me on the right path. I really appreciate it.
